### ISSUE TITLE
[Feature] 검색 알고리즘 개선

### ISSUE THREAD

**Issue by bamcasa** [Likelion-Festival/frontend#40]
**기능 요청이 문제와 관련이 있나요? 문제 설명**
검색알고리즘 개선 현재 데이터에서 해당 키워드의 존재유무로만 판별하여 필터링합니다.
그러면 예를 들어서 "무간판"이면 "무가"만 쳤을때 포함이 되지 않는 경우가 발생됩니다.
즉, 검색하는 도중에 주점을 찾을 수 없습니다 문구가 자꾸 뜨게 되고
또한 사용자가 원하는 결과를 잘 내보내지 못할 수 있습니다.

**원하는 해결책 설명**
https://taegon.kim/archives/9919
이와 같이 퍼지 문자열 검색을 활용하고 검색한 키워드를 다르게 표시하기
그리고 추가적으로 이름, 소속, 메뉴에 대해 다른 가중치를 주어 좀 더 세밀한 검색결과를 내보내도록 했으면 좋겠습니다.
**고려한 대안 설명**
퍼지 검색을 활용하거나
es-hangul 라이브러리(https://es-hangul.slash.page/docs/api/disassemble)를 통해서 모든 자음과 모음을 분리해서 존재유무를 판별하여 필터링하기
예를 들어서 "무간판"이면 "ㅁㅜㄱㅏㄴㅍㅏㄴ"으로 디스어셈블되고 "무가"만 쳐도 "ㅁㅜㄱㅏ"가 되니 키워드 존재유무 판별이 좀더 매끄러워질것 같습니다.

**예상 비용**
- **개발 시간**: es-hangul 라이브러리를 사용해서 자음 모음 분리해서 검색하는 것은 기존 로직을 사용하는 것이어서 오래 안 걸릴 것 같습니다.
그리고 퍼지 검색 알고리즘등의 다른 검색 알고리즘을 사용할 경우 오래 걸릴 것 같아 상황에 맞춰서 개발해주시면 감사하겠습니다.
- **기타 비용**: es-hangul등의 의존성 생김

**Comment by minjee2758** [comment]
disassemble 기능 설정 및 하이라이팅 기능 추가했습니다!
