### ISSUE TITLE
[BUG] 버튼 배경화면 다름

### ISSUE THREAD

**Issue by bamcasa** [Likelion-Festival/frontend#41]
**버그 설명**
커다란 버그는 아니고 버튼들의 배경화면이 검은색으로 기존의 배경화면색과 맞지 않습니다.

**스크린샷**
![SmartSelect_20240924_003657_Chrome.jpg](https://github.com/user-attachments/assets/b68e9ec1-a511-455e-b718-df00dc895691)

**추가 내용**
간단한 내용이니 시간이 남으시면 해주시기 바랍니다

**Comment by vlmbuyd** [comment]
해당 사항 수정 완료했습니다
